repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.405
    hooks:
      - id: pyright
        language: system
        entry: pyright
        additional_dependencies: []  # example: type stubs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: ["."]
      - id: ruff-format
        args: ["--check", "."]
